import type { Metadata } from "next";
import { Dosis } from "next/font/google";
import "../styles/globals.scss";

const dosis = Dosis({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aprovei",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.co",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="icon" href="./favicon.ico" sizes="any" />
      </head>
      <body className={dosis.className}>{children}</body>
    </html>
  );
}
